// Code generated by ENTIQON.
// File: db/driver/db2.go
// Description: Provides DB2Dialect configuration for IBM DB2 databases.
// Since: v1.6.0

package driver

import "github.com/entiqon/db/driver/styling"

// NewDB2Dialect implements the Dialect interface for IBM DB2 databases.
//
// This dialect uses:
//   - Quoting style: "identifier"
//   - Placeholder style: :param (named)
//   - Aliasing support: optional `AS`
//   - RETURNING clause: partially supported (varies by version)
//   - UPSERT capability: supported via MERGE syntax
//
// See:
//   - https://www.ibm.com/docs/en/db2
//   - https://www.ibm.com/docs/en/db2/latest?topic=statements-merge
func NewDB2Dialect() Dialect {
	return &BaseDialect{
		Name:             "db2",
		QuoteStyle:       styling.QuoteDouble,
		PlaceholderStyle: styling.PlaceholderNamed,
		EnableAliasing:   true,
		EnableReturning:  true,
		EnableUpsert:     true,
	}
}

var _ Dialect = &BaseDialect{}
