// Code generated by ENTIQON.
// File: db/driver/firebird.go
// Description: Provides FirebirdDialect configuration for Firebird SQL.
// Since: v1.6.0

package driver

import "github.com/entiqon/db/driver/styling"

// NewFirebirdDialect implements the Dialect interface for Firebird SQL engines.
//
// This dialect uses:
//   - Quoting style: "identifier"
//   - Placeholder style: ?
//   - Aliasing support: optional `AS`
//   - RETURNING clause: supported
//   - UPSERT capability: limited, often requires custom logic
//
// See:
//   - https://firebirdsql.org/refdocs/langrefupd21-insert.html
//   - https://firebirdsql.org/file/documentation/reference_manuals/
func NewFirebirdDialect() Dialect {
	return &BaseDialect{
		Name:             "firebird",
		QuoteStyle:       styling.QuoteDouble,
		PlaceholderStyle: styling.PlaceholderQuestion,
		EnableAliasing:   true,
		EnableReturning:  true,
		EnableUpsert:     true,
	}
}

var _ Dialect = &BaseDialect{}
