// Code generated by ENTIQON.
// File: db/driver/generic.go
// Description: Provides fallback GenericDialect for unspecified SQL behavior.
// Since: v1.4.0

package driver

import "github.com/entiqon/entiqon/db/driver/styling"

// NewGenericDialect returns a BaseDialect instance representing a neutral,
// non-engine-specific SQL dialect.
//
// This dialect is used as a safe fallback when no explicit dialect is configured.
// It uses the following behavior:
//
//   - GetName: "generic"
//   - QuoteType: none
//   - PlaceholderStyle: "?" (unnumbered positional)
//   - SupportsUpsert: false
//   - EnableReturning: false
//
// This dialect should NOT be used for engine-specific SQL generation.
//
// Since: v1.4.0
// Updated: v1.4.0
func NewGenericDialect() Dialect {
	return &BaseDialect{
		Name:             "generic",
		QuoteStyle:       styling.QuoteNone,
		PlaceholderStyle: styling.PlaceholderQuestion,
		EnableAliasing:   false,
		EnableReturning:  false,
		EnableUpsert:     false,
	}
}

var _ Dialect = &BaseDialect{}
