// Code generated by ENTIQON.
// File: db/driver/mssql.go
// Description: Provides MSSQLDialect configuration for SQL Server-compatible databases.
// Since: v1.4.0

package driver

import "github.com/entiqon/entiqon/db/driver/styling"

// MSSQLDialect implements the Dialect interface for Microsoft SQL Server.
//
// This dialect uses:
//   - Bracket quoting: [identifier]
//   - Generic positional placeholders: ?
//   - No native UPSERT (uses MERGE or app logic)
//   - No native RETURNING clause (use OUTPUT instead)
//
// Since: v1.4.0
type MSSQLDialect struct {
	BaseDialect
}

// NewMSSQLDialect returns a new MSSQLDialect instance,
// preconfigured with SQL Server-compatible rules.
//
// Quoting style: [identifier]
// PlaceholderStyle style: ?
// SupportsUpsert: false
// EnableReturning: false
//
// Since: v1.4.0
func NewMSSQLDialect() *MSSQLDialect {
	return &MSSQLDialect{
		BaseDialect{
			Name:             "mssql",
			QuoteStyle:       styling.QuoteBracket,
			PlaceholderStyle: styling.PlaceholderQuestion,
			EnableAliasing:   true,
			EnableReturning:  false,
			EnableUpsert:     false,
		},
	}
}

var _ Dialect = &BaseDialect{}
