// Code generated by ENTIQON.
// File: db/driver/mysql.go
// Description: Provides MySQLDialect configuration for MySQL-compatible databases.
// Since: v1.4.0

package driver

import "github.com/entiqon/db/driver/styling"

// MySQLDialect implements the Dialect interface for MySQL-compatible databases.
//
// This dialect uses:
//   - Backtick quoting: `identifier`
//   - Generic positional placeholders: ?
//   - No native UPSERT (requires ON DUPLICATE KEY UPDATE)
//   - No RETURNING clause
//
// Since: v1.4.0
type MySQLDialect struct {
	BaseDialect
}

// NewMySQLDialect returns a new MySQLDialect instance,
// preconfigured with MySQL-compatible rules.
//
// Quoting style: `identifier`
// PlaceholderStyle style: ?
// SupportsUpsert: false
// EnableReturning: false
//
// Since: v1.4.0
func NewMySQLDialect() *MySQLDialect {
	return &MySQLDialect{
		BaseDialect: BaseDialect{
			Name:             "mysql",
			QuoteStyle:       styling.QuoteBacktick,
			PlaceholderStyle: styling.PlaceholderQuestion,
			EnableAliasing:   true,
			EnableReturning:  false,
			EnableUpsert:     false,
		},
	}
}

var _ Dialect = &BaseDialect{}
