// Code generated by ENTIQON.
// File: db/driver/oracle.go
// Description: Provides OracleDialect configuration for Oracle-compatible databases.
// Since: v1.6.0

package driver

import "github.com/entiqon/entiqon/db/driver/styling"

// NewOracleDialect implements the Dialect interface for Oracle databases.
//
// Oracle uses named parameters (e.g., :param), standard double-quote identifiers,
// and supports RETURNING clauses. UPSERT logic is available using `MERGE INTO`.
// Note that SQL syntax can differ significantly depending on Oracle version.
//
// This dialect uses:
//   - Quoting style: "identifier"
//   - Placeholder style: :param
//   - Aliasing support: optional `AS`
//   - RETURNING clause: enabled
//   - UPSERT capability: enabled via MERGE INTO
//
// See:
//   - https://docs.oracle.com/en/database/
//   - https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/MERGE.html
//   - https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/RETURNING-INTO-Clause.html
func NewOracleDialect() Dialect {
	return &BaseDialect{
		Name:             "Oracle",
		QuoteStyle:       styling.QuoteDouble,
		PlaceholderStyle: styling.PlaceholderNamed, // e.g., :param
		EnableAliasing:   true,
		EnableReturning:  true,
		EnableUpsert:     true,
	}
}

var _ Dialect = &BaseDialect{}
