// Code generated by ENTIQON.
// File: db/driver/postgres.go
// Description: Provides PostgresDialect configuration for PostgreSQL-compatible databases.
// Since: v1.4.0

package driver

import "github.com/entiqon/db/driver/styling"

// PostgresDialect implements the Dialect interface for PostgreSQL-compatible databases.
//
// This dialect uses:
//   - Double quote quoting: "identifier"
//   - Positional dollar placeholders: $1, $2, ...
//   - Full support for native UPSERT (ON CONFLICT)
//   - Full support for RETURNING clauses
//
// Since: v1.4.0
type PostgresDialect struct {
	BaseDialect
}

// NewPostgresDialect returns a new PostgresDialect instance,
// preconfigured with PostgreSQL-compatible rules.
//
// Quoting style: "identifier"
// PlaceholderStyle style: $1, $2, ...
// SupportsUpsert: true
// EnableReturning: true
//
// Since: v1.4.0
func NewPostgresDialect() *PostgresDialect {
	return &PostgresDialect{
		BaseDialect: BaseDialect{
			Name:             "postgres",
			QuoteStyle:       styling.QuoteDouble,
			PlaceholderStyle: styling.PlaceholderDollar,
			EnableAliasing:   true,
			EnableReturning:  true,
			EnableUpsert:     true,
		},
	}
}

var _ Dialect = &BaseDialect{}
