// Code generated by ENTIQON.
// File: internal/core/driver/quote.go
// Description: Provides the QuoteStyle enum used to define how dialects quote identifiers.
// Since: v1.4.0

package styling

// QuoteStyle defines the quoting style used by a SQL dialect for identifiers
// such as table names, column names, and aliases.
type QuoteStyle string

const (
	// QuoteNone indicates that no quoting is applied to identifiers.
	QuoteNone QuoteStyle = "none"

	// QuoteDouble uses standard double quotes: "identifier"
	// Common in PostgreSQL, ANSI SQL.
	QuoteDouble QuoteStyle = "double"

	// QuoteBacktick uses backticks: `identifier`
	// Common in MySQL and SQLite.
	QuoteBacktick QuoteStyle = "backtick"

	// QuoteBracket uses square brackets: [identifier]
	// Common in Microsoft SQL Server.
	QuoteBracket QuoteStyle = "bracket"
)
