coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "internal/test/"
  - "**/*_mock.go"
  - "**/mocks/**"
  - "**/examples/**"