# use a pinned version for consistency
FROM squidfunk/mkdocs-material:9.4.7

WORKDIR /project

COPY mkdocs.yml requirements.txt ./

# Stage documentation content and maintain folder structure
RUN mkdir -p docs-site/dev/builder docs-site/dev/core docs-site/releases

COPY docs/documentation-infra.md docs-site/
COPY docs/index.md docs-site/index.md
COPY CHANGELOG.md docs-site/
COPY docs/dev/ docs-site/dev/
COPY releases/ docs-site/releases/

EXPOSE 8000

CMD ["serve", "--dev-addr=0.0.0.0:8000"]