FROM squidfunk/mkdocs-material

WORKDIR /project

COPY mkdocs.yml .
RUN mkdir -p docs/dev/builder docs/dev/core docs/releases && echo "Docs directories created"
RUN pwd
COPY docs docs/
# Copy docs folder excluding docs/releases (excluded by .dockerignore)
COPY CHANGELOG.md docs/
# Copy package READMEs as guides
COPY README.md                             docs/packages/overview.md
COPY common/README.md                      docs/packages/common/overview.md
COPY common/errors/README.md               docs/packages/common/errors/overview.md
COPY common/extension/boolean/README.md    docs/packages/common/extension/boolean.md
COPY common/extension/date/README.md       docs/packages/common/extension/date.md
COPY common/extension/decimal/README.md    docs/packages/common/extension/decimal.md
COPY common/extension/float/README.md      docs/packages/common/extension/float.md
COPY common/extension/integer/README.md    docs/packages/common/extension/integer.md
COPY common/extension/number/README.md     docs/packages/common/extension/number.md
COPY common/extension/object/README.md     docs/packages/common/extension/object.md
COPY common/extension/collection/README.md docs/packages/common/extension/collection.md
COPY db/README.md                          docs/packages/db/overview.md
COPY db/builder/README.md                  docs/packages/db/builder/overview.md
COPY db/contract/README.md                 docs/packages/db/contract/overview.md
COPY db/token/README.md                    docs/packages/db/token/overview.md
COPY db/token/field/README.md              docs/packages/db/token/field.md
COPY db/token/table/README.md              docs/packages/db/token/table.md
COPY db/token/join/README.md               docs/packages/db/token/join.md
COPY db/token/helpers/README.md            docs/packages/db/token/helpers.md
COPY releases/ docs/releases/
RUN echo "Documentation content copied"

EXPOSE 8000

CMD ["serve", "--dev-addr=0.0.0.0:8000"]
