// Code generated by ENTIQON.
// File: internal/core/contracts/generic.go
// Description: Defines a generic token interface for name mutation.
// Since: v1.6.0

package contract

// Generic is a minimal “generic” interface that exposes a single mutator:
// SetName, which overrides the parsed identifier of a token.
// BaseToken and any wrapper around it automatically satisfy this interface.
type Generic interface {
	// SetName replaces the internal parsed identifier.
	// Nil receiver → no-op.
	//
	// Example:
	//
	//     var g Generic = token.NewBaseToken("users.email AS u")
	//     g.SetName("email")
	//     fmt.Println(g.( *token.BaseToken ).GetName()) // Output: email
	SetName(name string)
}
