// Code generated by ENTIQON.
// File: internal/core/errors/stage_token.go
// Description: Enumerates builder stages used in error tagging.
// Since: v1.5.0

package error

// StageToken defines a standardized builder stage used to tag validation errors.
// These are used to associate specific parts of a query (e.g., SELECT, FROM) with meaningful feedback.
type StageToken string

const (
	// StageUnknown represents an undefined or untagged error context.
	StageUnknown StageToken = "UNKNOWN"

	// StageSelect indicates errors related to the SELECT projection or fields.
	StageSelect StageToken = "SELECT"

	// StageFrom indicates errors related to the FROM clause or source tables.
	StageFrom StageToken = "FROM"

	// StageJoin indicates errors related to JOIN clauses (INNER, LEFT, etc.).
	StageJoin StageToken = "JOIN"

	// StageWhere indicates errors in the WHERE condition logic.
	StageWhere StageToken = "WHERE"

	// StageGroup indicates errors related to GROUP BY clause.
	StageGroup StageToken = "GROUP"

	// StageHaving indicates errors related to the HAVING clause, often used with aggregations.
	StageHaving StageToken = "HAVING"

	// StageOrder indicates errors related to ORDER BY clause.
	StageOrder StageToken = "ORDER"

	// StageLimit indicates issues with LIMIT clause or pagination logic.
	StageLimit StageToken = "LIMIT"

	// StageOffset indicates issues with OFFSET clause or pagination logic.
	StageOffset StageToken = "OFFSET"
)

// String returns the stage name as a string.
// Implements fmt.Stringer.
func (s StageToken) String() string {
	return string(s)
}
