
contact_links:
  - name: 🤔 Questions, General Support, and Help
    url: https://github.com/entiqon/entiqon/blob/main/docs/documentation_issue.md
    about: This issue tracker is not for support questions. Please refer to the support documentation.
