// Code generated by ENTIQON.
// File: db/internal/core/errors/stage_token.go
// Description: Enumerates builder stages used in error tagging.
// Since: v1.5.0

package errors

// StageToken defines a standardized builder stage used to tag validation errors.
// These are used to associate specific parts of a query (e.g., SELECT, FROM) with meaningful feedback.
type StageToken string

const (
	// StageUnknown represents an undefined or untagged error context.
	StageUnknown StageToken = "UNKNOWN"

	// StageSelect indicates errors related to the SELECT projection or fields.
	StageSelect StageToken = "SELECT"

	// StageSet indicates errors related to the SET projection or fields.
	StageSet StageToken = "SET"

	// StageFrom indicates errors related to the FROM clause or source tables.
	StageFrom StageToken = "FROM"

	// StageInto indicates errors related to the INTO clause or source tables.
	StageInto StageToken = "INTO"

	// StageValues indicates errors related to the VALUES clause or source tables.
	StageValues StageToken = "VALUES"

	// StageJoin indicates errors related to JOIN clauses (INNER, LEFT, etc.).
	StageJoin StageToken = "JOIN"

	// StageWhere indicates errors in the WHERE condition logic.
	StageWhere StageToken = "WHERE"

	// StageGroup indicates errors related to GROUP BY clause.
	StageGroup StageToken = "GROUP"

	// StageHaving indicates errors related to the HAVING clause, often used with aggregations.
	StageHaving StageToken = "HAVING"

	// StageOrder indicates errors related to ORDER BY clause.
	StageOrder StageToken = "ORDER"

	// StageLimit indicates issues with LIMIT clause or pagination logic.
	StageLimit StageToken = "LIMIT"

	// StageOffset indicates issues with OFFSET clause or pagination logic.
	StageOffset StageToken = "OFFSET"

	// StageReturning indicates issues with RETURNING clause logic.
	StageReturning StageToken = "RETURNING"
)

// knownStageTokens contains all recognized StageToken values.
var knownStageTokens = map[StageToken]struct{}{
	StageSelect:    {},
	StageSet:       {},
	StageFrom:      {},
	StageInto:      {},
	StageJoin:      {},
	StageWhere:     {},
	StageReturning: {},
	StageGroup:     {},
	StageHaving:    {},
	StageOrder:     {},
	StageLimit:     {},
	StageOffset:    {},
}

// String returns the string representation of the StageToken.
//
// If the token is one of the known stage constants, the method returns its string value.
// If it is unrecognized, it returns "UNKNOWN" to ensure safe fallback behavior.
//
// Implements fmt.Stringer.
//
// Example:
//
//	var s StageToken = StageJoin
//	fmt.Println(s.String()) // Output: "JOIN"
//
//	var invalid StageToken = "UNTRACKED"
//	fmt.Println(invalid.String()) // Output: "UNKNOWN"
//
// Since: v1.4.0
func (s StageToken) String() string {
	if _, ok := knownStageTokens[s]; ok {
		return string(s)
	}
	return "UNKNOWN"
}
