// Code generated by ENTIQON.
// File: internal/core/driver/generic.go
// Description: Defines the default fallback dialect with generic behavior.
// Since: v1.4.0

package driver

// NewGenericDialect returns a BaseDialect instance representing a neutral,
// non-engine-specific SQL dialect.
//
// This dialect is used as a safe fallback when no explicit dialect is configured.
// It uses the following behavior:
//
//   - GetName: "generic"
//   - QuoteType: none
//   - PlaceholderSymbol: "?" (unnumbered positional)
//   - SupportsUpsert: false
//   - EnableReturning: false
//
// This dialect should NOT be used for engine-specific SQL generation.
//
// Since: v1.4.0
// Updated: v1.4.0
func NewGenericDialect() Dialect {
	return &BaseDialect{
		Name:              "generic",
		Quotation:         QuoteNone,
		PlaceholderSymbol: PlaceholderQuestion,
		EnableAliasing:    false,
		EnableReturning:   false,
		EnableUpsert:      false,
	}
}
