// Code generated by ENTIQON.
// File: driver/informix.go
// Description: Provides InformixDialect configuration for IBM Informix databases.
// Since: v1.6.0

package driver

import "github.com/entiqon/entiqon/driver/styling"

// InformixDialect implements the Dialect interface for Informix databases.
//
// This dialect uses:
//   - Quoting style: "identifier"
//   - Placeholder style: ?
//   - Aliasing support: optional `AS`
//   - RETURNING clause: supported
//   - UPSERT capability: not natively supported; emulate with MERGE
//
// See:
//   - https://www.ibm.com/docs/en/informix-servers
func NewInformixDialect() Dialect {
	return &BaseDialect{
		Name:             "informix",
		QuoteStyle:       styling.QuoteDouble,
		PlaceholderStyle: styling.PlaceholderQuestion,
		EnableAliasing:   true,
		EnableReturning:  true,
		EnableUpsert:     false,
	}
}

var _ Dialect = &BaseDialect{}
