// Code generated by ENTIQON.
// File: internal/core/driver/mssql.go
// Description: Provides MSSQLDialect definition and initialization.
// Since: v1.4.0

package driver

import "github.com/ialopezg/entiqon/driver/styling"

// MSSQLDialect implements the Dialect interface for Microsoft SQL Server.
//
// This dialect uses:
//   - Bracket quoting: [identifier]
//   - Generic positional placeholders: ?
//   - No native UPSERT (uses MERGE or app logic)
//   - No native RETURNING clause (use OUTPUT instead)
//
// Since: v1.4.0
type MSSQLDialect struct {
	BaseDialect
}

// NewMSSQLDialect returns a new MSSQLDialect instance,
// preconfigured with SQL Server-compatible rules.
//
// Quoting style: [identifier]
// PlaceholderSymbol style: ?
// SupportsUpsert: false
// EnableReturning: false
//
// Since: v1.4.0
func NewMSSQLDialect() *MSSQLDialect {
	return &MSSQLDialect{
		BaseDialect{
			Name:              "mssql",
			Quotation:         styling.QuoteBracket,
			PlaceholderSymbol: PlaceholderQuestion,
			EnableAliasing:    true,
			EnableReturning:   false,
			EnableUpsert:      false,
		},
	}
}
