// Code generated by ENTIQON.
// File: internal/core/driver/quote.go
// Description: Provides the QuotationType enum used to define how dialects quote identifiers.
// Since: v1.4.0

package driver

// QuotationType defines the quoting style used by a SQL dialect for identifiers
// such as table names, column names, and aliases.
type QuotationType string

const (
	// QuoteNone indicates that no quoting is applied to identifiers.
	QuoteNone QuotationType = "none"

	// QuoteDouble uses standard double quotes: "identifier"
	// Common in PostgreSQL, ANSI SQL.
	QuoteDouble QuotationType = "double"

	// QuoteBacktick uses backticks: `identifier`
	// Common in MySQL and SQLite.
	QuoteBacktick QuotationType = "backtick"

	// QuoteBracket uses square brackets: [identifier]
	// Common in Microsoft SQL Server.
	QuoteBracket QuotationType = "bracket"
)
