// Code generated by ENTIQON.
// File: internal/core/driver/dialect_postgres.go
// Description: Provides PostgresDialect definition and initialization.
// Since: v1.4.0

package driver

import (
	"fmt"
)

// PostgresDialect implements the Dialect interface for PostgreSQL-compatible databases.
//
// This dialect uses:
//   - Double quote quoting: "identifier"
//   - Positional dollar placeholders: $1, $2, ...
//   - Full support for native UPSERT (ON CONFLICT)
//   - Full support for RETURNING clauses
//
// Since: v1.4.0
type PostgresDialect struct {
	BaseDialect
}

// NewPostgresDialect returns a new PostgresDialect instance,
// preconfigured with PostgreSQL-compatible rules.
//
// Quoting style: "identifier"
// Placeholder style: $1, $2, ...
// SupportsUpsert: true
// SupportsReturning: true
//
// Since: v1.4.0
func NewPostgresDialect() *PostgresDialect {
	return &PostgresDialect{
		BaseDialect: BaseDialect{
			name:      "postgres",
			quotation: QuoteDouble,
			placeholder: func(index int) string {
				return fmt.Sprintf("$%d", index)
			},
			supportsReturning: true,
			supportsUpsert:    true,
		},
	}
}
