// Code generated by ENTIQON.
// File: internal/core/driver/dialect_generic.go
// Description: Defines the default fallback dialect with generic behavior.
// Since: v1.4.0

package driver

// NewGenericDialect returns a BaseDialect instance representing a neutral,
// non-engine-specific SQL dialect.
//
// This dialect is used as a safe fallback when no explicit dialect is configured.
// It uses the following behavior:
//
//   - Name: "generic"
//   - Quotation: none
//   - Placeholder: "?" (unnumbered positional)
//   - SupportsUpsert: false
//   - SupportsReturning: false
//
// This dialect should NOT be used for engine-specific SQL generation.
//
// Since: v1.4.0
// Updated: v1.4.0
func NewGenericDialect() Dialect {
	return &BaseDialect{
		name:      "generic",
		quotation: QuoteNone,
		placeholder: func(_ int) string {
			return "?"
		},
		supportsUpsert:    false,
		supportsReturning: false,
	}
}
