// Code generated by ENTIQON.
// File: internal/core/driver/dialect_mssql.go
// Description: Provides MSSQLDialect definition and initialization.
// Since: v1.4.0

package driver

// MSSQLDialect implements the Dialect interface for Microsoft SQL Server.
//
// This dialect uses:
//   - Bracket quoting: [identifier]
//   - Generic positional placeholders: ?
//   - No native UPSERT (uses MERGE or app logic)
//   - No native RETURNING clause (use OUTPUT instead)
//
// Since: v1.4.0
type MSSQLDialect struct {
	BaseDialect
}

// NewMSSQLDialect returns a new MSSQLDialect instance,
// preconfigured with SQL Server-compatible rules.
//
// Quoting style: [identifier]
// Placeholder style: ?
// SupportsUpsert: false
// SupportsReturning: false
//
// Since: v1.4.0
func NewMSSQLDialect() *MSSQLDialect {
	return &MSSQLDialect{
		BaseDialect{
			name:      "mssql",
			quotation: QuoteBracket,
			placeholder: func(_ int) string {
				return "?"
			},
			supportsUpsert:    false,
			supportsReturning: false,
		},
	}
}
